### ISSUE TITLE
couldn't digest ActiveSupport::StringInquirer

### ISSUE THREAD

**Issue by hakunin** [rails/sprockets#262]
Hi,
I am getting this strange issue and none of my co-workers have it on the same codebase.

I am able to get to the root of it, thanks to better errors - I can see that there is "development" there, which is from Rails.env (ActiveSupport::StringInquirer instance) but I have no idea how it got there, or how to debug / fix this.

Also, I found that foreman had this issue as well:
https://github.com/theforeman/foreman/pull/3038

Any ideas?

![screenshot 2016-03-11 10 49 24](https://cloud.githubusercontent.com/assets/65846/13698841/f9c20828-e776-11e5-8419-ccb410eae17b.png)

**Comment by rafaelfranca** [comment]
Which Rails version are you using? Which sprockets-rails version are you using?

**Comment by hakunin** [comment]
Sorry, somehow I overlooked the notification. Its
```
rails 4.2.5.1
sprockets 3.5.2
sprockets-rails 3.0.1
```

**Comment by rafaelfranca** [comment]
Could you check if cleaning the sprocekts cache fix the issue? `rm -Rf tmp/cache/assets`

**Comment by hakunin** [comment]
Hah, I thought I did that already, but apparently not. That fixed my problem, thanks!

**Comment by JDutil** [comment]
I've been running into this occasionally with some co-workers since upgrading to `rails 4.2.6`, `sprockets 3.5.2`, `sprockets-rails 3.0.4`. The problem tends to pop up after switching branches or modifying asset files.

We never experienced this until updating to the latest sprockets, and it's getting pretty annoying however removing `tmp/cache/assets` does temporarily fix the problem.

**Comment by rafaelfranca** [comment]
The problem is that sprockets-rails < 3.0.4 is being polluting the cache with wrong values that was fixed with sprockets-rails 3.0.4. Make sure that all your branches will be using sprockets-rails 3.0.4, clean the cache and this will never happen again.

**Comment by huoxito** [comment]
@rafaelfranca removing / cleaning up the rails-app/tmp dir doesn't fix it for long, I've removed it many times today alone and the issue keeps coming back, setting `assets.debug` back to true seems to make the issue go away. I'll try to gather more info and will post here if it keeps happening even with `assets.debug` true

**Comment by rafaelfranca** [comment]
Are you sure that you always run the code using `sprockets-rails 3.0.4` after you cleaned the cache?

**Comment by huoxito** [comment]
I'm not sure if this is the proper answer for that question but this is all I have sprockets related on Gemfile:

```
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.0.4)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
```

I do have other versions installed locally but I trust bundler is loading the right one:

```
*** LOCAL GEMS ***
sprockets (3.5.2, 3.3.5, 3.3.3)
sprockets-rails (3.0.4, 3.0.3, 2.3.3, 2.3.2)
```

It could be latest sprocket plus something specific to this particular rails application since it's happening pretty often in dev mode (whenever assets, apparently css files mostly, are updated) and I guess if it's a big issue we would see more bug reports. I'll get back here with when I get more info thanks @rafaelfranca :beers:

**Comment by rafaelfranca** [comment]
To try to help you what were writing `StringInquirer` in the cache was removed in this commit https://github.com/rails/sprockets-rails/commit/9a61447e1c34ed6d35c358935bcae4522b60b48d#diff-b295f4f07d2e863f15e53eb2047cfd1fR116.
