### ISSUE TITLE
No source map indication

### ISSUE THREAD

**Issue by julik** [rails/sprockets#70]
Currently Sprockets (after the merge of 4.x) does not output any sourcemap indications. It does not output an `X-SourceMap` header and does not append a source map reference URL to the compiled assets. This while the `.map` suffixed route is available and served.

I had to introduce a middleware to set the header, but this is probably not the way it is supposed to work.
https://github.com/julik/4perf/blob/master/hacks/expose_sourcemaps_via_header.rb

**Comment by rafaelfranca** [comment]
This should be fixed now

**Comment by julik** [comment]
I have updated to the latest git ref and it is definitely not fixed. There is no source map comment and no header for:
[]CoffeeScript
[]ES6
[]Sass

**Comment by Andreis13** [comment]
@julik , the source map comment is appended when the asset is requested through the `:debug` pipeline

**Comment by julik** [comment]
@Andreis13 ok, and how do I set that up or trigger it from the URL?

**Comment by Andreis13** [comment]
For example: if you have a file `application.js`, you can get the debug version by linking to `application.debug.js`.
Who knows.. maybe in the future there will be a more convenient way to do this..
